spring:
  application:
    name: service-article-html
  profiles:
    active: dev

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  freemarker:
    charset: UTF-8
    template-loader-path: classpath:/templates
    suffix: .ftl
    content-type: text/html

  rabbitmq:
    host: 43.142.253.194
    port: 5672
    username: admin
    password: 123


#    jedis:
#      pool:
#        max-active: 8   # 连接池最大连接数（使用负值表示没有限制）
#    # 连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-wait: -1
#    # 连接池中的最大空闲连接
#        max-idle: 8
#    # 连接池中的最小空闲连接
#        min-idle: 0


freemarker:
  html:
#    targert: C:/workspace/imooc-news/article-html
    targert: D:/Java_install/tomcat/apache-tomcat-9.0.65/webapps/imooc-news/portal/articlehtml