spring:
  application:
    name: service-search
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/imooc-news-dev?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  elasticsearch:
    rest:
      username: esuser
      uris: http://43.142.253.194:9200

eureka:
  server:
    hostname: eureka
    port: 7000
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.server.hostname}:${eureka.server.port}/eureka/
  instance:
    lease-renewal-interval-in-seconds: 5000
    lease-expiration-duration-in-seconds: 5000








