server:
  port: 8003

spring:
  redis:
    port: 6379
    database: 0
    host: localhost
    password:
    timeout: 5000

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


