spring:
  application:
    name: service-file
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  servlet:
    multipart:
      max-file-size: 512000
      max-request-size: 512000

fdfs:
  connect-timeout: 30
  tracker-list: 192.168.91.129:22122
  so-timeout: 30
