server:
  port: 8001

spring:
  redis:
    port: 6379
    database: 0
    host: localhost
    password:
    timeout: 5000


website:
  domain-name: imooc-news.com
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
