spring:
  application:
    name: service-file
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/imooc-news-dev?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver


#    jedis:
#      pool:
#        max-active: 8   # 连接池最大连接数（使用负值表示没有限制）
#    # 连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-wait: -1
#    # 连接池中的最大空闲连接
#        max-idle: 8
#    # 连接池中的最小空闲连接
#        min-idle: 0


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      # 主键生成策略
      id-type: ASSIGN_ID